name: Arkadas Otomatik Takip

on:
  schedule:
    - cron: '0 */7 * * *' # 5 saatte bir çalışır
  workflow_dispatch: 

jobs:
  auto-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests beautifulsoup4

      - name: Run Auto Script
        env:
          USERNAME: ${{ secrets.Onur_USERNAME }}
          PASSWORD: ${{ secrets.Onur_PASSWORD }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.Onur_USERNAME }}
        run: python yulearn_arkadas.py
