name: Yulearn Bildirim Botu

on:
  schedule:
    - cron: '0 */7 * * *' # Her 5 saatte bir çalışır
  workflow_dispatch: # Actions sekmesinden manuel tetikleme butonu ekler

jobs:
  check-yulearn:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Yulearn Script
        env:
          MOODLE_COOKIE: ${{ secrets.MOODLE_COOKIE }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          ONUR_COOKIE: ${{ secrets.ONUR_COOKIE }}
          ONUR_EMAIL: ${{ secrets.ONUR_EMAIL }}
        run: python yulearn.py 

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add yulearn_scraping_state.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: yulearn durumu guncellendi" && git pull --rebase origin main && git push)
